{
  username,
  config,
  ...
}:
{
  users.mutableUsers = true;

  users.groups = {
    "${username}" = { };
    docker = { };
    wireshark = { };
    plugdev = { };
  };

  users.users."${username}" = {
    # generated by `mkpasswd -m scrypt`
    home = "/home/${username}";
    isNormalUser = true;
    extraGroups = [
      username
      "users"
      "networkmanager"
      "wheel"
      "docker"
      "wireshark"
      "adbusers"
      "libvirtd"
      "gamoemode"
    ];
  };
}
