{
  username,
  config,
  ...
}: {
  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  users.groups = {
    "${username}" = {};
    docker = {};
    wireshark = {};
    plugdev = {};
  };

  users.users."${username}" = {
    # generated by `mkpasswd -m scrypt`
    home = "/home/${username}";
    initialHashedPassword = "$7$CU..../....e31GdGo1FaxZwIOTqR/Np0$WY4osB0ItKNlgdutmxtpYjhaXdnzdnRHY8.WlyGNwH/";
    isNormalUser = true;
    extraGroups = [
      username
      "users"
      "networkmanager"
      "wheel"
      "docker"
      "wireshark"
      "adbusers"
      "libvirtd"
    ];
  };
  users.users.root = {
    initialHashedPassword = config.users.users."${username}".initialHashedPassword;
  };
}
